import React, { useReducer, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { initialJourney, isTrackingCodeValid, journeyReducer } from './demo/journey.js';
import './styles.css';
import './journey-extensions.css';

const mobileNumber = '۰۹۳۵ ۷۴۲ ۱۸۶۳';
const requestId = 'NC-FD-240815-793';
const steps = [
  { title: 'پرداخت هزینه نماینده', short: 'هزینه', caption: 'فعال‌سازی فرایند برای نماینده' },
  { title: 'جست‌وجوی کاربر', short: 'جست‌وجو', caption: 'ورود شماره همراه کاربر نیوکش' },
  { title: 'شروع درخواست', short: 'درخواست', caption: 'انتخاب کاربر و ایجاد پرونده' },
  { title: 'تخصیص شماره موقت', short: 'شماره', caption: 'شماره قانونی و یک‌بارمصرف' },
  { title: 'تأیید پیامک فیدا', short: 'پیامک', caption: 'دریافت کد از پنل نیوکاش' },
  { title: 'تکمیل هویت کاربر', short: 'هویت', caption: 'همراه با کاربر در پرتال فیدا' },
  { title: 'تخصیص کارت پرداخت', short: 'کارت', caption: 'ابزار پرداخت موقت نیوکاش' },
  { title: 'رمز پویا و پرداخت', short: 'پرداخت', caption: 'تأیید پرداخت در درگاه بانک' },
  { title: 'تأیید اطلاعات کاربر', short: 'پاسپورت', caption: 'شماره نیوکش و شماره پاسپورت' },
  { title: 'ثبت کد پیگیری', short: 'ثبت نهایی', caption: 'تحویل رسید پرداخت به نیوکاش' },
];

function Icon({ name, size = 20 }) {
  const paths = {
    home: <><path d="m3 11 9-7 9 7v9a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-9Z" /><path d="M9 21v-6h6v6" /></>,
    users: <><circle cx="9" cy="8" r="3" /><path d="M3.5 20c.6-3.1 2.4-4.7 5.5-4.7s4.9 1.6 5.5 4.7" /><path d="M16 5.5a3 3 0 0 1 0 5M17 15.6c2.1.4 3.3 1.8 3.7 4.4" /></>,
    file: <><path d="M6 3h8l4 4v14H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2V5a2 2 0 0 1 2-2Z" /><path d="M14 3v5h5M8 13h8M8 17h6" /></>,
    wallet: <><rect x="3" y="6" width="18" height="14" rx="3" /><path d="M3 10h18M16 15h2" /><path d="M6 6V5a2 2 0 0 1 2-2h9" /></>,
    help: <><circle cx="12" cy="12" r="9" /><path d="M9.8 9a2.4 2.4 0 1 1 3.8 2c-1.1.8-1.6 1.2-1.6 2.5" /><path d="M12 17h.01" /></>,
    bell: <><path d="M18 10a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 22h4" /></>,
    chevron: <path d="m9 18 6-6-6-6" />, arrow: <path d="M5 12h14m-6-6 6 6-6 6" />, check: <path d="m5 12 4.2 4.2L19.5 6" />,
    copy: <><rect x="8" y="8" width="11" height="12" rx="2" /><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h2" /></>,
    shield: <><path d="M12 3 20 6v5c0 5.1-3.4 8.7-8 10-4.6-1.3-8-4.9-8-10V6l8-3Z" /><path d="m8.5 12 2.2 2.2 4.8-5" /></>,
    clock: <><circle cx="12" cy="12" r="9" /><path d="M12 7v5l3.3 2" /></>, lock: <><rect x="5" y="10" width="14" height="11" rx="2" /><path d="M8 10V7a4 4 0 0 1 8 0v3" /></>,
    external: <><path d="M14 4h6v6M20 4l-9 9" /><path d="M17 13v5a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h5" /></>, card: <><rect x="3" y="5" width="18" height="14" rx="2" /><path d="M3 10h18M7 15h3" /></>,
    phone: <><rect x="7" y="3" width="10" height="18" rx="2" /><path d="M11 18h2" /></>, refresh: <><path d="M20 11a8 8 0 0 0-14.6-3.7L3 10" /><path d="M3 4v6h6M4 13a8 8 0 0 0 14.6 3.7L21 14" /><path d="M21 20v-6h-6" /></>,
    menu: <><path d="M4 7h16M4 12h16M4 17h16" /></>, bank: <><path d="m3 10 9-6 9 6M5 10v8m4-8v8m6-8v8m4-8v8M3 21h18M2 18h20" /></>, info: <><circle cx="12" cy="12" r="9" /><path d="M12 11v5M12 8h.01" /></>,
  };
  return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}

function StatusPill({ tone = 'teal', children }) { return <span className={`status-pill ${tone}`}><i />{children}</span>; }
function PrimaryButton({ children, className = '', ...props }) { return <button className={`button primary ${className}`} {...props}>{children}</button>; }

function Sidebar({ onReset }) {
  const nav = [['home', 'خانه'], ['users', 'کاربران'], ['file', 'فیدا برای کاربران'], ['wallet', 'تسویه و پرداخت'], ['help', 'راهنما و پشتیبانی']];
  return <aside className="sidebar"><div className="brand"><span className="brand-mark"><b>n</b></span><div><strong>نیو‌کش</strong><small>پنل نمایندگان</small></div></div><div className="workspace-label">فضای کاری نماینده</div><nav>{nav.map(([icon, label]) => <button key={label} className={`nav-item ${label === 'فیدا برای کاربران' ? 'active' : ''}`}><Icon name={icon} size={18} /><span>{label}</span>{label === 'فیدا برای کاربران' && <i className="nav-dot" />}</button>)}</nav><div className="sidebar-footer"><div className="support-card"><span className="support-icon"><Icon name="shield" size={16} /></span><div><b>پشتیبانی نمایندگان</b><small>۰۲۱-۹۱۰۹-۲۰۷۰</small></div></div><button className="reset-link" onClick={onReset}><Icon name="refresh" size={15} />شروع مجدد دمو</button></div></aside>;
}

function Topbar() { return <header className="topbar"><button className="mobile-menu" aria-label="منو"><Icon name="menu" /></button><div className="breadcrumb"><span>نمایندگان</span><Icon name="chevron" size={15} /><strong>ایجاد فیدا</strong><em>دموی داخلی</em></div><div className="top-actions"><button className="notification" aria-label="اعلان‌ها"><Icon name="bell" size={19} /><i /></button><div className="agent-mini"><span>م</span><div><b>مریم احمدی</b><small>نماینده سطح ۲</small></div></div></div></header>; }

function Progress({ step, onStep }) { return <div className="progress-wrap"><div className="progress-label"><span>مسیر درخواست فیدا</span><small>مرحله <b>{step}</b> از ۱۰</small></div><div className="progress-steps">{steps.map((item, index) => { const number = index + 1; const done = number < step; const current = number === step; return <button key={item.title} onClick={() => number <= step && onStep(number)} className={`progress-step ${done ? 'done' : ''} ${current ? 'current' : ''}`} disabled={number > step}><span>{done ? <Icon name="check" size={14} /> : number}</span><b>{item.short}</b></button>; })}</div></div>; }

function UserProfile({ journey }) {
  const identified = journey.passportCaptured;
  return <section className={`profile-card ${identified ? 'identified' : 'unidentified'}`}><div className="profile-top"><div className="avatar large">{identified ? 'س' : '?'}</div><div>{<span className="eyebrow">{identified ? 'کاربر تأییدشدهٔ نیوکش' : 'کاربر نامشخص'}</span>}<h3>{identified ? 'سارا محمدی' : 'هویت هنوز تأیید نشده'}</h3><p>{identified ? 'شناسه کاربری: NC-48372' : 'پس از تطبیق شماره و پاسپورت نمایش داده می‌شود'}</p></div><StatusPill tone={identified ? 'teal' : 'amber'}>{identified ? 'هویت فیدا تأیید شد' : 'در انتظار احراز فیدا'}</StatusPill></div><div className="profile-data"><div><span>شماره ملی</span><b>{identified ? '۰۰۷•••••۳۹' : '••••••••••'}</b></div><div><span>شماره همراه اصلی</span><b>{identified ? '۰۹۱۲ •••• ۶۴۰۹' : 'پس از احراز هویت'}</b></div><div><span>وضعیت فیدا</span><b className={identified ? 'text-teal' : ''}>{identified ? 'تأیید و آماده ثبت' : 'ناشناس'}</b></div></div></section>;
}

function SecureCodeCard({ kind, copied, onCopy }) {
  const content = kind === 'sms' ? { label: 'کد پیامک فیدا', code: '۴۸ ۶۹ ۳۱', expiry: 'تا ۰۸:۴۲ معتبر است', icon: 'phone', note: 'این کد فقط برای ورود در پرتال فیدا استفاده شود.' } : { label: 'رمز پویای کارت موقت', code: '۷۲ ۴۸ ۶۶', expiry: 'تا ۰۱:۵۸ معتبر است', icon: 'lock', note: 'رمز را در درگاه پرداخت وارد کنید؛ آن را به شخص دیگری ندهید.' };
  return <div className={`secure-code ${kind}`}><div className="secure-code-head"><span className="secure-icon"><Icon name={content.icon} size={18} /></span><div><span>{content.label}</span><small><Icon name="clock" size={12} />{content.expiry}</small></div><StatusPill tone="blue">ارسال شد</StatusPill></div><div className="code-row"><strong dir="ltr">{content.code}</strong><button onClick={onCopy} className={copied ? 'copied' : ''}><Icon name={copied ? 'check' : 'copy'} size={17} />{copied ? 'کپی شد' : 'کپی کد'}</button></div><p><Icon name="shield" size={14} />{content.note}</p></div>;
}

function LegacyOperationsRail({ journey }) {
  const timeline = [['پرونده فیدا ایجاد شد', 'همین حالا', 'done'], ['شماره موقت تخصیص یافت', journey.step >= 2 ? 'انجام شد' : 'در انتظار', journey.step >= 2 ? 'done' : ''], ['تأیید پیامک فیدا', journey.smsReady ? 'کد آماده است' : 'در انتظار', journey.smsReady ? 'done' : ''], ['ابزار پرداخت موقت', journey.step >= 5 ? 'تخصیص داده شد' : 'در انتظار', journey.step >= 5 ? 'done' : '']];
  return <aside className="operations"><section className="request-card"><div className="card-kicker"><span>وضعیت عملیاتی</span><StatusPill tone="blue">در جریان</StatusPill></div><h3>درخواست ایجاد فیدا</h3><div className="request-id"><span>شناسه درخواست</span><b>{requestId}</b></div><div className="request-owner"><div className="avatar">م</div><div><span>مسئول پرونده</span><b>مریم احمدی</b></div></div></section><section className="rail-section"><div className="rail-heading"><span>منابع تخصیص‌یافته</span><Icon name="shield" size={16} /></div><div className={`resource ${journey.step >= 2 ? 'ready' : ''}`}><span className="resource-icon"><Icon name="phone" size={17} /></span><div><small>شماره موقت قانونی</small><b>{journey.step >= 2 ? mobileNumber : 'پس از شروع درخواست'}</b></div><StatusPill tone={journey.step >= 2 ? 'teal' : 'gray'}>{journey.step >= 2 ? 'رزرو شده' : 'آماده‌سازی'}</StatusPill></div><div className={`resource ${journey.step >= 5 ? 'ready' : ''}`}><span className="resource-icon"><Icon name="card" size={17} /></span><div><small>کارت پرداخت موقت</small><b>{journey.step >= 5 ? '۶۰۳۷ ۹۹•• •••• ۸۴۴۱' : 'پس از تکمیل هویت'}</b></div><StatusPill tone={journey.step >= 5 ? 'teal' : 'gray'}>{journey.step >= 5 ? 'تخصیص یافت' : 'قفل است'}</StatusPill></div></section><section className="rail-section timeline-section"><div className="rail-heading"><span>ردیابی فرآیند</span><small>زنده</small></div><ol className="timeline">{timeline.map(([label, time, state]) => <li key={label} className={state}><i>{state === 'done' ? <Icon name="check" size={11} /> : ''}</i><div><b>{label}</b><small>{time}</small></div></li>)}</ol></section><div className="privacy-note"><Icon name="lock" size={15} /><span>تمام اطلاعات نمایشی، نمونه و مخصوص این دمو هستند.</span></div></aside>;
}

function OperationsRail({ journey }) {
  const timeline = [
    ['هزینه نماینده', journey.representativePaid ? 'دریافت شد' : 'در انتظار', journey.representativePaid],
    ['جست‌وجوی کاربر', journey.userLocated ? 'کاربر پیدا شد' : 'در انتظار', journey.userLocated],
    ['شماره موقت فیدا', journey.step >= 4 ? 'تخصیص یافت' : 'در انتظار', journey.step >= 4],
    ['رمز پویا و پاسپورت', journey.passportCaptured ? 'تأیید شد' : 'در انتظار', journey.passportCaptured],
  ];
  return <aside className="operations"><section className="request-card"><div className="card-kicker"><span>وضعیت عملیاتی</span><StatusPill tone="blue">در جریان</StatusPill></div><h3>درخواست ایجاد فیدا</h3><div className="request-id"><span>شناسه درخواست</span><b>{requestId}</b></div><div className="request-owner"><div className="avatar">م</div><div><span>مسئول پرونده</span><b>مریم احمدی</b></div></div></section><section className="rail-section"><div className="rail-heading"><span>منابع تخصیص‌یافته</span><Icon name="shield" size={16} /></div><div className={`resource ${journey.step >= 4 ? 'ready' : ''}`}><span className="resource-icon"><Icon name="phone" size={17} /></span><div><small>شماره موقت قانونی</small><b>{journey.step >= 4 ? mobileNumber : 'پس از ایجاد درخواست'}</b></div><StatusPill tone={journey.step >= 4 ? 'teal' : 'gray'}>{journey.step >= 4 ? 'رزرو شده' : 'آماده‌سازی'}</StatusPill></div><div className={`resource ${journey.step >= 7 ? 'ready' : ''}`}><span className="resource-icon"><Icon name="card" size={17} /></span><div><small>کارت پرداخت موقت</small><b>{journey.step >= 7 ? '۶۰۳۷ ۹۹•• •••• ۸۴۴۱' : 'پس از تکمیل هویت'}</b></div><StatusPill tone={journey.step >= 7 ? 'teal' : 'gray'}>{journey.step >= 7 ? 'تخصیص یافت' : 'قفل است'}</StatusPill></div></section><section className="rail-section timeline-section"><div className="rail-heading"><span>ردیابی فرآیند</span><small>زنده</small></div><ol className="timeline">{timeline.map(([label, time, done]) => <li key={label} className={done ? 'done' : ''}><i>{done ? <Icon name="check" size={11} /> : ''}</i><div><b>{label}</b><small>{time}</small></div></li>)}</ol></section><div className="privacy-note"><Icon name="lock" size={15} /><span>تمام اطلاعات نمایشی، نمونه و مخصوص این دمو هستند.</span></div></aside>;
}

function StepShell({ number, children, dispatch }) { const item = steps[number - 1]; return <section className="wizard-card"><div className="step-heading"><div className="step-number">۰{number}</div><div><span className="eyebrow">{item.caption}</span><h1>{item.title}</h1></div>{number > 1 && <button className="back-button" onClick={() => dispatch({ type: 'BACK' })}><Icon name="arrow" size={16} />بازگشت</button>}</div>{children}</section>; }

function LegacyStepContent({ journey, dispatch, setOverlay, copied, setCopied, trackingCode, setTrackingCode, completed, setCompleted }) {
  const copy = (kind) => { setCopied(kind); window.setTimeout(() => setCopied(''), 1800); };
  if (journey.step === 1) return <StepShell number={1} dispatch={dispatch}><div className="intro-grid"><div><p className="lead">برای دریافت کد فیدا برای سارا محمدی، یک پرونده‌ی جدید بسازید. نیوکش شماره و ابزار پرداخت موقت را فقط در طول این درخواست در اختیار شما قرار می‌دهد.</p><div className="notice info"><Icon name="info" size={19} /><div><b>این فرایند با حضور کاربر انجام می‌شود</b><span>مسئولیت تکمیل اطلاعات هویتی در پرتال فیدا با نماینده و کاربر است.</span></div></div><PrimaryButton onClick={() => dispatch({ type: 'NEXT' })}>ایجاد درخواست و ادامه<Icon name="arrow" size={18} /></PrimaryButton></div><div className="request-preview"><span className="preview-label">نمای کلی درخواست</span><div><Icon name="file" size={28} /><strong>ایجاد فیدا برای کاربر موجود</strong><small>بدون نیاز به ثبت‌نام مجدد کاربر در نیوکش</small></div><dl><dt>کاربر</dt><dd>سارا محمدی</dd><dt>ارائه‌دهنده</dt><dd>فیدا</dd><dt>نماینده</dt><dd>مریم احمدی</dd></dl></div></div></StepShell>;
  if (journey.step === 2) return <StepShell number={2} dispatch={dispatch}><p className="lead">یک شماره همراه موقت و قانونی برای ورود اولیه در فیدا به این پرونده تخصیص داده شده است.</p><div className="allocation-card phone-allocation"><div className="allocation-top"><span className="allocation-icon"><Icon name="phone" size={25} /></span><div><span>شماره همراه موقت</span><strong dir="ltr">{mobileNumber}</strong></div><StatusPill tone="teal">تخصیص یافت</StatusPill></div><div className="allocation-meta"><span><Icon name="clock" size={14} />رزرو تا پایان این درخواست</span><span><Icon name="shield" size={14} />کاربری محدود و مجاز</span></div></div><div className="notice amber"><Icon name="shield" size={19} /><div><b>نحوه استفاده</b><span>شماره را در پرتال فیدا وارد کنید. کد پیامک دریافتی به‌طور امن در همین پنل نمایش داده می‌شود.</span></div></div><PrimaryButton onClick={() => setOverlay('fida')}>ورود به پرتال فیدا<Icon name="external" size={17} /></PrimaryButton></StepShell>;
  if (journey.step === 3) return <StepShell number={3} dispatch={dispatch}><p className="lead">فیدا کد ورود را به شماره موقت ارسال کرده است. کد را کپی و در پرتال فیدا وارد کنید.</p><SecureCodeCard kind="sms" copied={copied === 'sms'} onCopy={() => copy('sms')} /><div className="two-col-note"><div><Icon name="check" size={19} /><span><b>کد ارسال شد</b>دریافت پیامک از مسیر امن نیوکش تأیید شد.</span></div><div><Icon name="users" size={19} /><span><b>کاربر کنار شماست؟</b>مراحل تکمیل هویت باید با حضور کاربر انجام شود.</span></div></div><PrimaryButton onClick={() => dispatch({ type: 'NEXT' })}>کد را در فیدا وارد کردم<Icon name="arrow" size={18} /></PrimaryButton></StepShell>;
  if (journey.step === 4) return <StepShell number={4} dispatch={dispatch}><p className="lead">در این مرحله، تکمیل اطلاعات و احراز هویت در پرتال فیدا با حضور کاربر انجام می‌شود. پس از پایان، وضعیت را در این پنل ثبت کنید.</p><div className="identity-list">{['تطبیق مشخصات فردی با کاربر', 'ثبت اطلاعات موردنیاز در پرتال فیدا', 'تأیید نهایی مراحل ثبت‌نام توسط کاربر'].map((item, index) => <div key={item}><span>{index + 1}</span><b>{item}</b><small>{index === 0 ? 'با مدرک شناسایی معتبر' : index === 1 ? 'خارج از پنل نیوکش' : 'پیش از درخواست پرداخت'}</small></div>)}</div><div className="notice info"><Icon name="info" size={19} /><div><b>حریم خصوصی کاربر</b><span>اطلاعات هویتی فیدا در نیوکش ذخیره نمی‌شود؛ فقط وضعیت تکمیل فرایند ثبت می‌شود.</span></div></div><PrimaryButton onClick={() => dispatch({ type: 'IDENTITY_COMPLETED' })}>مراحل ثبت‌نام را تکمیل کردم<Icon name="check" size={18} /></PrimaryButton></StepShell>;
  if (journey.step === 5) return <StepShell number={5} dispatch={dispatch}><p className="lead">اطلاعات هویت تکمیل شد. برای پرداخت هزینه فیدا، از کارت موقت تخصیص‌یافته فقط در همین درگاه استفاده کنید.</p><div className="allocation-card card-allocation"><div className="card-chip" /><div className="card-logo">نیو‌کش <small>Demo card</small></div><div className="card-number" dir="ltr">۶۰۳۷ ۹۹•• •••• ۸۴۴۱</div><div className="card-bottom"><span>نام دارنده<br /><b>NewCash Temporary</b></span><span>انقضا<br /><b>۰۹ / ۰۷</b></span></div></div><div className="notice amber"><Icon name="shield" size={19} /><div><b>فقط برای این پرداخت</b><span>از اطلاعات کارت برای خرید یا پرداخت دیگری استفاده نکنید. اعتبار کارت پس از پایان فرایند آزاد می‌شود.</span></div></div><PrimaryButton onClick={() => setOverlay('payment')}>ورود به درگاه پرداخت<Icon name="external" size={17} /></PrimaryButton></StepShell>;
  if (journey.step === 6) return <StepShell number={6} dispatch={dispatch}><p className="lead">در درگاه بانکی درخواست رمز پویا ثبت شده است. رمز را از پنل کپی کرده و در درگاه وارد کنید؛ سپس منتظر کد پیگیری پرداخت بمانید.</p><SecureCodeCard kind="otp" copied={copied === 'otp'} onCopy={() => copy('otp')} /><div className="gateway-status"><span className="status-ring"><Icon name="bank" size={21} /></span><div><b>درگاه در انتظار تأیید شماست</b><small>رمز پویا را وارد کنید و پس از مشاهده پرداخت موفق، کد پیگیری را بردارید.</small></div><StatusPill tone="amber">در انتظار پرداخت</StatusPill></div><PrimaryButton onClick={() => dispatch({ type: 'NEXT' })}>پرداخت موفق شد، کد پیگیری دارم<Icon name="arrow" size={18} /></PrimaryButton></StepShell>;
  return <StepShell number={7} dispatch={dispatch}>{completed ? <SuccessReceipt onReset={() => { setCompleted(false); setTrackingCode(''); dispatch({ type: 'RESET' }); }} /> : <><p className="lead">کد پیگیری نمایش‌داده‌شده در درگاه بانکی را وارد کنید تا پرداخت به پرونده کاربر متصل و درخواست ثبت نهایی شود.</p><div className="tracking-form"><label htmlFor="tracking">کد پیگیری پرداخت <em>*</em></label><div><input id="tracking" value={trackingCode} onChange={(event) => setTrackingCode(event.target.value)} placeholder="مثال: ۸۶۴۲۰۹۷۱" inputMode="numeric" /><span>{trackingCode.length}/۶</span></div>{trackingCode && !isTrackingCodeValid(trackingCode) && <small className="field-error">کد پیگیری باید دست‌کم ۶ کاراکتر داشته باشد.</small>}</div><div className="notice info compact"><Icon name="lock" size={18} /><div><b>ثبت امن رسید</b><span>کد برای تطبیق پرداخت استفاده می‌شود و جایگزین اطلاعات کارت نیست.</span></div></div><PrimaryButton disabled={!isTrackingCodeValid(trackingCode)} onClick={() => setCompleted(true)}>ثبت نهایی درخواست<Icon name="check" size={18} /></PrimaryButton></>}</StepShell>;
}

function StepFrame({ number, dispatch, children }) {
  const item = steps[number - 1];
  return <section className="wizard-card"><div className="step-heading"><div className="step-number">{number < 10 ? `۰${number}` : '۱۰'}</div><div><span className="eyebrow">{item.caption}</span><h1>{item.title}</h1></div>{number > 1 && <button className="back-button" onClick={() => dispatch({ type: 'BACK' })}><Icon name="arrow" size={16} />بازگشت</button>}</div>{children}</section>;
}

function StepContent({ journey, dispatch, setOverlay, copied, setCopied, trackingCode, setTrackingCode, completed, setCompleted, searchPhone, setSearchPhone, passport, setPassport }) {
  const copy = (kind) => { setCopied(kind); window.setTimeout(() => setCopied(''), 1800); };
  const hasValidPhone = /^۰?۹\d{9}$/.test(searchPhone.replace(/[\s-]/g, '')) || /^0?9\d{9}$/.test(searchPhone.replace(/[\s-]/g, ''));
  const hasPassport = passport.trim().length >= 6;
  const simpleNotice = (title, text) => <div className="notice info"><Icon name="info" size={19} /><div><b>{title}</b><span>{text}</span></div></div>;

  if (journey.step === 1) return <StepFrame number={1} dispatch={dispatch}><p className="lead">پیش از شروع فرایند ایجاد فیدا، هزینهٔ خدمت از نماینده دریافت و برای این درخواست ثبت می‌شود.</p><div className="demo-payment"><div><span className="payment-mark"><Icon name="wallet" size={22} /></span><div><small>هزینه فعال‌سازی خدمت فیدا</small><b>۱۸۰٬۰۰۰ ریال</b><em>پرداخت‌کننده: مریم احمدی · نماینده سطح ۲</em></div><StatusPill tone="amber">در انتظار دریافت</StatusPill></div><div className="payment-lines"><span>شرح خدمت <b>ایجاد فیدا برای کاربر نیوکش</b></span><span>روش دریافت <b>اعتبار نماینده</b></span></div></div>{simpleNotice('پرداخت نمایشی است', 'در این دمو فقط وضعیت دریافت هزینه ثبت می‌شود و تراکنش واقعی انجام نمی‌گیرد.')}<PrimaryButton onClick={() => dispatch({ type: 'REPRESENTATIVE_PAYMENT_COMPLETED' })}>دریافت هزینه از نماینده<Icon name="check" size={18} /></PrimaryButton></StepFrame>;

  if (journey.step === 2) return <StepFrame number={2} dispatch={dispatch}><p className="lead">شماره همراهی را وارد کنید که کاربر با آن در نیوکش ثبت شده است. پیدا شدن شماره، به‌تنهایی به‌معنی تأیید هویت نیست.</p><div className="lookup-form"><label htmlFor="newcash-phone">شماره همراه کاربر در نیوکش <em>*</em></label><div><span><Icon name="phone" size={18} /></span><input id="newcash-phone" value={searchPhone} onChange={(event) => setSearchPhone(event.target.value)} placeholder="مثال: ۰۹۱۲ ۱۲۳ ۴۵۶۷" inputMode="tel" dir="ltr" /></div>{searchPhone && !hasValidPhone && <small className="field-error">شماره همراه را با ۱۱ رقم وارد کنید.</small>}</div>{hasValidPhone && <div className="matched-user"><span className="avatar large">?</span><div><small>رکورد اولیه در نیوکش پیدا شد</small><b>هویت کاربر هنوز ناشناس است</b><em>پس از احراز فیدا و ثبت پاسپورت مشخص می‌شود</em></div><StatusPill tone="amber">نیازمند احراز</StatusPill></div>}<PrimaryButton disabled={!hasValidPhone} onClick={() => dispatch({ type: 'USER_LOCATED' })}>ادامه برای ایجاد پرونده<Icon name="arrow" size={18} /></PrimaryButton></StepFrame>;

  if (journey.step === 3) return <StepFrame number={3} dispatch={dispatch}><p className="lead">پرونده اولیه ایجاد می‌شود، اما هنوز هیچ کاربر مشخصی برای این درخواست تأیید نشده است. احراز واقعی در فیدا انجام خواهد شد.</p><div className="request-preview"><span className="preview-label">نمای کلی درخواست</span><div><Icon name="file" size={28} /><strong>پرونده کاربر ناشناس</strong><small>شماره همراه فقط برای شروع تطبیق ثبت شده است.</small></div><dl><dt>کاربر</dt><dd>نامشخص</dd><dt>ارائه‌دهنده</dt><dd>فیدا</dd><dt>نماینده</dt><dd>مریم احمدی</dd></dl></div>{simpleNotice('اطلاعات هویتی هنوز در دسترس نیست', 'تا زمان تکمیل احراز فیدا، نام و مشخصات کاربر در پنل نمایش داده نمی‌شود.')}<PrimaryButton onClick={() => dispatch({ type: 'NEXT' })}>ایجاد درخواست و ادامه<Icon name="arrow" size={18} /></PrimaryButton></StepFrame>;

  if (journey.step === 4) return <StepFrame number={4} dispatch={dispatch}><p className="lead">یک شماره همراه موقت و قانونی برای ورود اولیه در فیدا به این پرونده تخصیص داده شده است.</p><div className="allocation-card phone-allocation"><div className="allocation-top"><span className="allocation-icon"><Icon name="phone" size={25} /></span><div><span>شماره همراه موقت</span><strong dir="ltr">{mobileNumber}</strong></div><StatusPill tone="teal">تخصیص یافت</StatusPill></div><div className="allocation-meta"><span><Icon name="clock" size={14} />رزرو تا پایان این درخواست</span><span><Icon name="shield" size={14} />کاربری محدود و مجاز</span></div></div>{simpleNotice('نحوه استفاده', 'شماره را در پرتال فیدا وارد کنید. کد پیامک دریافتی به‌طور امن در همین پنل نمایش داده می‌شود.')}<PrimaryButton onClick={() => setOverlay('fida')}>ورود به پرتال فیدا<Icon name="external" size={17} /></PrimaryButton></StepFrame>;

  if (journey.step === 5) return <StepFrame number={5} dispatch={dispatch}><p className="lead">فیدا کد ورود را به شماره موقت ارسال کرده است. کد را کپی و در پرتال فیدا وارد کنید.</p><SecureCodeCard kind="sms" copied={copied === 'sms'} onCopy={() => copy('sms')} />{simpleNotice('کاربر کنار شماست؟', 'مراحل تکمیل هویت باید با حضور کاربر انجام شود.')}<PrimaryButton onClick={() => dispatch({ type: 'NEXT' })}>کد را در فیدا وارد کردم<Icon name="arrow" size={18} /></PrimaryButton></StepFrame>;

  if (journey.step === 6) return <StepFrame number={6} dispatch={dispatch}><p className="lead">در این مرحله، تکمیل اطلاعات و احراز هویت در پرتال فیدا با حضور کاربر انجام می‌شود. پس از پایان، وضعیت را در این پنل ثبت کنید.</p><div className="identity-list">{['تطبیق مشخصات فردی با کاربر', 'ثبت اطلاعات موردنیاز در پرتال فیدا', 'تأیید نهایی مراحل ثبت‌نام توسط کاربر'].map((item, index) => <div key={item}><span>{index + 1}</span><b>{item}</b><small>{index === 0 ? 'با مدرک شناسایی معتبر' : index === 1 ? 'خارج از پنل نیوکش' : 'پیش از درخواست پرداخت'}</small></div>)}</div>{simpleNotice('حریم خصوصی کاربر', 'اطلاعات هویتی فیدا در نیوکش ذخیره نمی‌شود؛ فقط وضعیت تکمیل فرایند ثبت می‌شود.')}<PrimaryButton onClick={() => dispatch({ type: 'IDENTITY_COMPLETED' })}>مراحل ثبت‌نام را تکمیل کردم<Icon name="check" size={18} /></PrimaryButton></StepFrame>;

  if (journey.step === 7) return <StepFrame number={7} dispatch={dispatch}><p className="lead">اطلاعات هویت تکمیل شد. برای پرداخت هزینه فیدا، از کارت موقت تخصیص‌یافته فقط در همین درگاه استفاده کنید.</p><div className="allocation-card card-allocation"><div className="card-chip" /><div className="card-logo">نیو‌کش <small>Demo card</small></div><div className="card-number" dir="ltr">۶۰۳۷ ۹۹•• •••• ۸۴۴۱</div><div className="card-bottom"><span>نام دارنده<br /><b>NewCash Temporary</b></span><span>انقضا<br /><b>۰۹ / ۰۷</b></span></div></div>{simpleNotice('فقط برای این پرداخت', 'از اطلاعات کارت برای خرید یا پرداخت دیگری استفاده نکنید. اعتبار کارت پس از پایان فرایند آزاد می‌شود.')}<PrimaryButton onClick={() => setOverlay('payment')}>ورود به درگاه پرداخت<Icon name="external" size={17} /></PrimaryButton></StepFrame>;

  if (journey.step === 8) return <StepFrame number={8} dispatch={dispatch}><p className="lead">در درگاه بانکی درخواست رمز پویا ثبت شده است. رمز را از پنل کپی کرده و در درگاه وارد کنید.</p><SecureCodeCard kind="otp" copied={copied === 'otp'} onCopy={() => copy('otp')} /><div className="gateway-status"><span className="status-ring"><Icon name="bank" size={21} /></span><div><b>درگاه در انتظار تأیید شماست</b><small>رمز پویا را وارد کنید؛ سپس به پنل برگردید و اطلاعات کاربر را تأیید کنید.</small></div><StatusPill tone="amber">در انتظار پرداخت</StatusPill></div><PrimaryButton onClick={() => dispatch({ type: 'OTP_USED' })}>رمز پویا را در درگاه وارد کردم<Icon name="check" size={18} /></PrimaryButton></StepFrame>;

  if (journey.step === 9) return <StepFrame number={9} dispatch={dispatch}><p className="lead">پس از استفاده از OTP، شمارهٔ ثبت‌شدهٔ کاربر در نیوکش را با خود او بررسی و شماره پاسپورتش را وارد کنید. هنوز نام کاربر در پنل آزاد نشده است.</p><div className="passport-card"><div className="passport-user"><span className="avatar large">?</span><div><small>شماره همراه کاربر در نیوکش</small><b dir="ltr">۰۹۱۲ ۴۸۳ ۶۴۰۹</b><em>رکورد اولیه · منتظر تطبیق فیدا</em></div><StatusPill tone="amber">احراز نشده</StatusPill></div><label className="passport-input" htmlFor="passport">شماره پاسپورت کاربر <em>*</em><input id="passport" value={passport} onChange={(event) => setPassport(event.target.value.toUpperCase())} placeholder="مثال: A12345678" dir="ltr" /></label>{passport && !hasPassport && <small className="field-error">شماره پاسپورت باید دست‌کم ۶ کاراکتر داشته باشد.</small>}</div>{hasPassport && <div className="identity-confirmed"><Icon name="shield" size={18} /><span><b>احراز فیدا تکمیل شد</b>اکنون اطلاعات هویتی برای ادامهٔ پرونده قابل نمایش است.</span></div>}<PrimaryButton disabled={!hasPassport} onClick={() => dispatch({ type: 'PASSPORT_CAPTURED' })}>تأیید هویت و ادامه<Icon name="arrow" size={18} /></PrimaryButton></StepFrame>;

  return <StepFrame number={10} dispatch={dispatch}>{completed ? <SuccessReceipt onReset={() => { setCompleted(false); setTrackingCode(''); dispatch({ type: 'RESET' }); }} /> : <><p className="lead">کد پیگیری نمایش‌داده‌شده در درگاه بانکی را وارد کنید تا پرداخت به پرونده کاربر متصل و درخواست ثبت نهایی شود.</p><div className="tracking-form"><label htmlFor="tracking">کد پیگیری پرداخت <em>*</em></label><div><input id="tracking" value={trackingCode} onChange={(event) => setTrackingCode(event.target.value)} placeholder="مثال: ۸۶۴۲۰۹۷۱" inputMode="numeric" /><span>{trackingCode.length}/۶</span></div>{trackingCode && !isTrackingCodeValid(trackingCode) && <small className="field-error">کد پیگیری باید دست‌کم ۶ کاراکتر داشته باشد.</small>}</div>{simpleNotice('ثبت امن رسید', 'کد برای تطبیق پرداخت استفاده می‌شود و جایگزین اطلاعات کارت نیست.')}<PrimaryButton disabled={!isTrackingCodeValid(trackingCode)} onClick={() => setCompleted(true)}>ثبت نهایی درخواست<Icon name="check" size={18} /></PrimaryButton></>}</StepFrame>;
}

function SuccessReceipt({ onReset }) { return <div className="success-receipt"><div className="success-seal"><Icon name="check" size={34} /></div><span className="eyebrow">پرداخت با موفقیت ثبت شد</span><h2>درخواست فیدا آماده پیگیری است</h2><p>کد پرداخت به پرونده سارا محمدی متصل شد و تیم نیوکش وضعیت درخواست را بررسی می‌کند.</p><div className="receipt-grid"><div><span>شناسه درخواست</span><b>{requestId}</b></div><div><span>کد پیگیری</span><b>ثبت شد</b></div><div><span>وضعیت</span><b className="text-teal">در صف بررسی</b></div></div><button className="button outline" onClick={onReset}><Icon name="refresh" size={17} />شروع یک دمو جدید</button></div>; }

function Modal({ type, onClose, onComplete }) {
  const fida = type === 'fida';
  const body = fida ? (
    <div className="modal-body"><div className="portal-title"><span className="portal-step">۱ از ۳</span><h2>ورود با شماره همراه</h2><p>شماره همراه تخصیص‌یافته از نیوکش را وارد کنید.</p></div><label className="portal-field">شماره همراه<input value={mobileNumber} readOnly dir="ltr" /><small>این شماره در طول فرایند به‌طور موقت به پرونده شما متصل است.</small></label><button className="button portal-primary" onClick={onComplete}>ارسال کد تأیید<Icon name="arrow" size={18} /></button><p className="portal-security"><Icon name="lock" size={14} />ارتباط امن و رمزنگاری‌شده</p></div>
  ) : (
    <div className="modal-body"><div className="merchant"><span>FIDA</span><div><b>هزینه ثبت‌نام فیدا</b><small>پذیرنده: خدمات هویت دیجیتال</small></div><strong>۱۸۰٬۰۰۰ <small>ریال</small></strong></div><div className="gateway-form"><label>شماره کارت<input value="۶۰۳۷ ۹۹•• •••• ۸۴۴۱" readOnly dir="ltr" /></label><div><label>تاریخ انقضا<input value="۰۹ / ۰۷" readOnly /></label><label>CVV2<input value="•••" readOnly /></label></div></div><div className="otp-request"><div><span className="otp-dot" /><div><b>رمز پویا</b><small>رمز را از پنل نیوکش دریافت کنید.</small></div></div></div><button className="button portal-primary" onClick={onComplete}>درخواست رمز پویا<Icon name="lock" size={17} /></button></div>
  );
  return <div className="modal-backdrop" role="presentation"><section className={`external-modal ${fida ? 'fida-modal' : 'gateway-modal'}`} role="dialog" aria-modal="true" aria-label={fida ? 'پرتال فیدا' : 'درگاه پرداخت'}><div className="external-bar"><div className="external-brand">{fida ? <><span className="fida-symbol">ف</span><b>فیدا</b><small>سامانه هویت دیجیتال</small></> : <><span className="gateway-symbol"><Icon name="bank" size={17} /></span><b>پرداخت امن</b><small>درگاه بانکی</small></>}</div><span className="simulation-tag">شبیه‌سازی در دمو</span><button className="close-modal" onClick={onClose} aria-label="بستن">×</button></div>{body}</section></div>;
}

function App() {
  const [journey, dispatch] = useReducer(journeyReducer, initialJourney); const [overlay, setOverlay] = useState(null); const [copied, setCopied] = useState(''); const [trackingCode, setTrackingCode] = useState(''); const [completed, setCompleted] = useState(false); const [searchPhone, setSearchPhone] = useState(''); const [passport, setPassport] = useState('');
  const reset = () => { dispatch({ type: 'RESET' }); setOverlay(null); setCopied(''); setTrackingCode(''); setCompleted(false); setSearchPhone(''); setPassport(''); };
  const finishOverlay = () => { if (overlay === 'fida') dispatch({ type: 'FIDA_PORTAL_COMPLETED' }); else dispatch({ type: 'PAYMENT_GATEWAY_COMPLETED' }); setOverlay(null); };
  return <div className="newcash-app" dir="rtl"><Sidebar onReset={reset} /><div className="main-area"><Topbar /><main className="content"><div className="page-intro"><div><span className="eyebrow">عملیات فیدا</span><h1>ایجاد فیدا برای کاربر نیوکش</h1><p>همراه کاربر، مراحل ثبت‌نام و پرداخت را به‌صورت امن تکمیل کنید.</p></div><StatusPill tone="blue">محیط نمایشی</StatusPill></div><Progress step={journey.step} onStep={(step) => dispatch({ type: 'GO_TO_STEP', step })} /><div className="console-grid"><div className="wizard-column"><UserProfile journey={journey} /><StepContent journey={journey} dispatch={dispatch} setOverlay={setOverlay} copied={copied} setCopied={setCopied} trackingCode={trackingCode} setTrackingCode={setTrackingCode} completed={completed} setCompleted={setCompleted} searchPhone={searchPhone} setSearchPhone={setSearchPhone} passport={passport} setPassport={setPassport} /></div><OperationsRail journey={journey} /></div></main><footer>نیو‌کش · محیط شبیه‌سازی برای نمایش فرایند · هیچ داده یا پرداخت واقعی در این صفحه پردازش نمی‌شود.</footer></div>{overlay && <Modal type={overlay} onClose={() => setOverlay(null)} onComplete={finishOverlay} />}</div>;
}

createRoot(document.getElementById('root')).render(<App />);
